### ISSUE TITLE
Remove udt4 from FC

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-2#26]
I guess it's safe to do so. See https://github.com/steemit/fc/commit/b07f42955666cc44571d9f527a4e540a5431fabf

**Comment by vikramrajkumar** [comment]
Already done:
* https://github.com/bitshares/bitshares-fc/commit/b07f42955666cc44571d9f527a4e540a5431fabf
* https://github.com/bitshares/bitshares-fc/commit/326140a9315970563c8a78834bad4ca2bb0d1fe2

Submodule will be updated soon to use this fc fork.
